### ISSUE TITLE
Empty application after following the instructions

### ISSUE THREAD

**Issue by AgaFra** [Problematy/goodmap-integration#6]
The app doesn't run properly after following the instructions. This is what I'm getting:
![obraz](https://user-images.githubusercontent.com/79878967/220202756-c6986740-a415-4999-be32-777007346f32.png)
![obraz](https://user-images.githubusercontent.com/79878967/220202841-2648e232-0bb5-4302-874b-00f214421bb5.png)
![obraz](https://user-images.githubusercontent.com/79878967/220203126-e4f2ff5c-ea4c-460c-8f76-9fd648d5a0b4.png)

**Comment by raven-wing** [comment]
Could you specify which command in the instruction?

**Comment by raven-wing** [comment]
This should be working from [this commit](https://github.com/Problematy/goodmap-integration/commit/361a1970640d5437f7a629c555b8c3874e952874)

**Comment by AgaFra** [comment]
> Could you specify which command in the instruction?
`
docker run -p 5000:5000 -p 8080:8080 -v YOUR-FRONTEND-DIRECTORY:/app/frontend/goodmap -v YOUR-BACKEND-DIRECTORY:/app/backend/goodmap goodmap main`

**Comment by AgaFra** [comment]
Still doesn't work. What's more now I get this same problem by using 
`docker run -p 5000:5000 -p 8080:8080 goodmap main`
which was working previously.
![obraz](https://user-images.githubusercontent.com/79878967/220472420-c1146012-6a1b-4259-9fe9-eb1ebbd80711.png)
